spring.application.name=FItMart
spring.data.mongodb.database=${MONGO_DATABASE}
spring.data.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
jwt.secret.key=7qYk9pQzL8mW3nY5vT7rJ4hG6fD2sK9eP0qN1tM8xR2uB4vC6w=
# Gi?i h?n t?i ?a file upload (ví d? 20MB)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB